### ISSUE TITLE
remove unnecessary parentheses crashes in some scenarios

### ISSUE THREAD

**Issue by rpau** [walkmod/walkmod-sonar-plugin#5]
An exeception has been produced during the null transformation -
```
org.walkmod.util.location.LocationImpl@de1b4dd
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.walkmod.walkers.AbstractWalker.walk(AbstractWalker.java:261)
at org.walkmod.walkers.AbstractWalker.execute(AbstractWalker.java:276)
at org.walkmod.javalang.walkers.DefaultJavaWalker.execute(DefaultJavaWalker.java:160)
at org.walkmod.impl.DefaultChainWalkerInvocation.invoke(DefaultChainWalkerInvocation.java:41)
at org.walkmod.impl.DefaultChainInvocation.invoke(DefaultChainInvocation.java:38)
at org.walkmod.impl.DefaultChainAdapter.execute(DefaultChainAdapter.java:165)
at org.walkmod.WalkModFacade.executeAllChains(WalkModFacade.java:911)
at org.walkmod.WalkModFacade.apply(WalkModFacade.java:376)
at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:171)
at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:196)
Caused by: java.lang.reflect.InvocationTargetException
... 15 more
Caused by: Error processing [/Users/acoroleu/dev/walkmod/hbase/hbase-protocol/src/main/java/org/apache/hadoop/hbase/protobuf/generated/AccessControlProtos.java] - org.walkmod.util.location.LocationImpl@32dca84b
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
at java.util.LinkedList$ListItr.next(LinkedList.java:888)
at org.walkmod.javalang.visitors.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:594)
at org.walkmod.javalang.ast.expr.ObjectCreationExpr.accept(ObjectCreationExpr.java:163)
at org.walkmod.javalang.visitors.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:189)
at org.walkmod.javalang.ast.expr.AssignExpr.accept(AssignExpr.java:107)

```

**Comment by rpau** [comment]
It cannot be reproducible.
